### ISSUE TITLE
amepd license

### ISSUE THREAD

**Issue by zeehio** [rhdunn/amepd#1]
Hi Reece,

I was reviewing the licence of each mimic file and I either I did not find the license terms for the amepd dictionary or they are vague enough to pose problems from a legal point of view. I found this amepd license terms:

```
 Use of this dictionary for any research or commercial purpose is completely
 unrestricted.  If you make use of or redistribute this material, we would
 appreciate acknowlegement of its origin.
```

On the other hand cmudict 0.7 (amepd is based on that as far as I know) has the following license:

```
;;; #
;;; # ========================================================================
;;; # Copyright (C) 1993-2015 Carnegie Mellon University. All rights reserved.
;;; #
;;; # Redistribution and use in source and binary forms, with or without
;;; # modification, are permitted provided that the following conditions
;;; # are met:
;;; #
;;; # 1. Redistributions of source code must retain the above copyright
;;; #    notice, this list of conditions and the following disclaimer.
;;; #    The contents of this file are deemed to be source code.
;;; #
;;; # 2. Redistributions in binary form must reproduce the above copyright
;;; #    notice, this list of conditions and the following disclaimer in
;;; #    the documentation and/or other materials provided with the
;;; #    distribution.
;;; #
;;; # This work was supported in part by funding from the Defense Advanced
;;; # Research Projects Agency, the Office of Naval Research and the National
;;; # Science Foundation of the United States of America, and by member
;;; # companies of the Carnegie Mellon Sphinx Speech Consortium. We acknowledge
;;; # the contributions of many volunteers to the expansion and improvement of
;;; # this dictionary.
;;; #
;;; # THIS SOFTWARE IS PROVIDED BY CARNEGIE MELLON UNIVERSITY ``AS IS'' AND
;;; # ANY EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
;;; # THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
;;; # PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY
;;; # NOR ITS EMPLOYEES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
;;; # SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
;;; # LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
;;; # DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
;;; # THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
;;; # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
;;; # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
;;; #
;;; # ========================================================================
;;; #
;;;
```

Note that the amepd license does not give permissions for any use other than `research or commercial purposes` (these two are the only purposes considered in the license).  Would you consider using the BSD-2 license as the cmudict does?

**Comment by rhdunn** [comment]
The amepd is derived from commit 7825 of http://svn.code.sf.net/p/cmusphinx/code/trunk/cmudict (the cmudict.0.7a file). This was before the dictionary changed to the BSD-2 license, so uses the license statement as described in cmudict 0.2.

I will switch to the BSD-2 license given your concerns over the `research or commercial purposes`, to align it with the more recent cmudict versions.

**Comment by zeehio** [comment]
Thanks! For clarification, if I want to use amepd "for fun" (not research and not a commercial purpose) I cannot do that because the license terms do not grant permission to use the dictionary for any other purpose. This silly issue makes amepd non-free source code.

On the other hand the BSD 2 license states "Redistribution and **use** in source and binary.. are permitted..." so under that license I can have as much fun with amepd as I want :smile:

**Comment by rhdunn** [comment]
I agree with your analysis, so have made the changes by merging in cmudict commit 8122, which was the point at which it switched to use the BSD-2 license.
